### PR TITLE
[kunlunxin] add Efficientnet config

### PR DESCRIPTION
**Pull request by ScoThunder**
性能日志
1x8：root@p-phy-h3c-klx-node-027:/data/dufeilei/zhiyuan/FlagPerf/training/result/run20231227233016/efficientnet:pytorch:R300:1:8:1/round1/192.167.5.27_noderank0
1x1: root@p-phy-h3c-klx-node-038:/data/dufeilei/zhiyuan/FlagPerf/training/result/run20231227232940/efficientnet:pytorch:R300:1:1:1/round1/192.167.5.38_noderank0
2x8:
root@p-phy-h3c-klx-node-038:/data/dufeilei/zhiyuan/FlagPerf/training/result/run20231228115723/efficientnet:pytorch:R300:2:8:1/round1/

精度日志
xpu 1x8：root@p-phy-h3c-klx-node-027:/data/dufeilei/zhiyuan/FlagPerf/training/result/run20231130113011/efficientnet:pytorch:R300:1:8:1/round1/192.167.5.27_noderank0
gpu 1x8: root@p-dgx-a100-158:/raid/dufeilei/FlagPerf/training/result/run20231220181545/efficientnet:pytorch_1.13:A100:1:8:1/round1/10.1.2.158_noderank0

### CODE REVIEW

**Comment by yuzhou03** [comment]
PR title前加上厂商 [kunlunxin]

**Review by shh2000 — APPROVED** [review]

**Comment by yuzhou03** [comment]
rebuild image && start container  2x8  【OK】

image

**Comment by yuzhou03** [comment]
1x8相对1x1的加速比为8.27.  
1x1的显存占用22.1/32.0，bs是否可以调大一些

**Comment by yuzhou03** [comment]
gov report 数据已完成
efficientnet-kunlunxin-1x1-fp32
efficientnet-kunlunxin-1x8-fp32
efficientnet-kunlunxin-2x8-fp32

**Review by yuzhou03 — APPROVED** [review]

**Pull request merged**
